const AUTH_LOGIN = 'AUTH_LOGIN';
const AUTH_LOGOUT = 'AUTH_LOGOUT';
const AUTH_UPDATE = 'AUTH_UPDATE';
const API_SET = 'API_SET';
const API_POST = 'API_POST';
const API_PATCH = 'API_PATCH';
const API_DELETE = 'API_DELETE';
const ONLINE = 'ONLINE';
const OFFLINE = 'OFFLINE';

export {
  AUTH_LOGIN,
  AUTH_LOGOUT,
  AUTH_UPDATE,
  API_SET,
  API_POST,
  API_PATCH,
  API_DELETE,
  ONLINE,
  OFFLINE
};
